# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=400, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('pin', models.CharField(max_length=255, null=True)),
                ('contact_no', models.CharField(max_length=10, null=True)),
                ('aadhaar_no', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncrementDetails',
            fields=[
                ('increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeDetails')),
            ],
        ),
        migrations.CreateModel(
            name='PayScale',
            fields=[
                ('designation', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('basic_pay', models.BigIntegerField()),
                ('HRA', models.BigIntegerField()),
                ('TA', models.BigIntegerField()),
                ('MA', models.BigIntegerField()),
                ('PF', models.BigIntegerField()),
                ('gross_pay', models.BigIntegerField()),
                ('net_pay', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.PayScale'),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.HotelDetails'),
        ),
    ]
