# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_guestdetails_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdetails',
            name='password',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
