# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='contact_no',
            field=models.CharField(max_length=255),
        ),
    ]
