# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20170827_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_status',
            field=models.CharField(choices=[('A', 'Availed'), ('B', 'Booked'), ('C1', 'Cancelled by user'), ('C2', 'Cancelled by hotel')], max_length=2),
        ),
    ]
